#pragma once

// Only the three fixtures generated by OfficeFixtures.Create are accepted.
// Successful output creation is an observation, not independent PDF validation.
bool OfficeExports(const fs::path& root, PSID sid, const std::vector<wchar_t>& environment) {
    const auto fixtures = root.parent_path() / L"office-fixtures";
    const auto executable = root.parent_path() / L"office" / L"program" / L"soffice.com";
    Grant(fixtures, sid, FILE_GENERIC_READ | FILE_GENERIC_EXECUTE);
    const auto previousMode = SetErrorMode(SEM_FAILCRITICALERRORS | SEM_NOGPFAULTERRORBOX | SEM_NOOPENFILEERRORBOX);
    struct ErrorModeGuard { UINT value; ~ErrorModeGuard() { SetErrorMode(value); } } errorMode{ previousMode };
    const std::wstring options = LR"({"UseLosslessCompression":{"type":"boolean","value":"true"},"ReduceImageResolution":{"type":"boolean","value":"false"},"UseTaggedPDF":{"type":"boolean","value":"true"},"ExportBookmarks":{"type":"boolean","value":"true"},"ExportNotes":{"type":"boolean","value":"false"},"ExportNotesPages":{"type":"boolean","value":"false"},"ExportOnlyNotesPages":{"type":"boolean","value":"false"},"ExportHiddenSlides":{"type":"boolean","value":"false"},"SinglePageSheets":{"type":"boolean","value":"false"},"ExportFormFields":{"type":"boolean","value":"false"},"IsAddStream":{"type":"boolean","value":"false"},"EncryptFile":{"type":"boolean","value":"false"},"ExportTrackedChanges":{"type":"boolean","value":"false"},"SelectPdfVersion":{"type":"long","value":"17"}})";
    struct Fixture { const wchar_t* family; const wchar_t* extension; const wchar_t* filter; const wchar_t* profile; };
    const Fixture cases[] = { { L"Word", L"docx", L"writer_pdf_Export", L"w" },
        { L"Excel", L"xlsx", L"calc_pdf_Export", L"x" }, { L"PowerPoint", L"pptx", L"impress_pdf_Export", L"p" } };
    bool passed = true;
    for (const auto& fixture : cases) for (const bool isolated : { false, true }) {
        const auto name = std::wstring(fixture.family) + (isolated ? L"-isolated" : L"-control");
        try {
            const auto profile = root / L"writable" / (std::wstring(fixture.profile) + (isolated ? L"i" : L"c"));
            const auto settings = profile / L"user" / L"registrymodifications.xcu";
            fs::create_directories(settings.parent_path());
            fs::copy_file(fixtures / L"settings.xcu", settings);
            const auto output = root / L"writable" / name;
            fs::create_directories(output);
            wchar_t uri[32768]{}; DWORD length = static_cast<DWORD>(std::size(uri));
            Require(SUCCEEDED(UrlCreateFromPathW(profile.c_str(), uri, &length, 0)), "Create owned export profile URI");
            const std::vector<std::wstring> common = { std::wstring(L"-env:UserInstallation=") + uri,
                L"--headless", L"--nologo", L"--nodefault", L"--norestore", L"--unaccept=all" };
            auto arguments = common; arguments.push_back(L"--terminate_after_init");
            const auto initialization = Run(executable, arguments, root, isolated ? sid : nullptr, 60000, {}, &environment);
            std::ofstream(root / (name + L"-init.log")) << initialization.output;
            std::ofstream(root / (name + L"-init.json")) << "{\"exitCode\":" << initialization.exitCode
                << ",\"timedOut\":" << (initialization.timedOut ? "true" : "false")
                << ",\"outputLimit\":" << (initialization.outputLimit ? "true" : "false")
                << ",\"totalProcesses\":" << initialization.totalProcesses << ",\"activeAfterCleanup\":0}\n";
            Require(initialization.exitCode == 0 && !initialization.timedOut && !initialization.outputLimit, "Office profile initialization");
            fs::copy_file(fixtures / L"settings.xcu", settings, fs::copy_options::overwrite_existing);
            const auto source = fixtures / (std::wstring(fixture.family) + L" \u00fc." + fixture.extension);
            arguments = common;
            arguments.insert(arguments.end(), { L"--convert-to", std::wstring(L"pdf:") + fixture.filter + L":" + options,
                L"--outdir", output.native(), source.native() });
            const auto result = Run(executable, arguments, root, isolated ? sid : nullptr, 60000, {}, &environment);
            std::ofstream(root / (name + L"-export.log")) << result.output;
            const auto pdf = output / (std::wstring(fixture.family) + L" \u00fc.pdf");
            const auto bytes = fs::is_regular_file(pdf) ? fs::file_size(pdf) : 0;
            const bool completed = result.exitCode == 0 && !result.timedOut && !result.outputLimit && bytes > 0 && bytes <= 16 * MiB;
            std::ofstream(root / (name + L"-export.json")) << "{\"completed\":" << (completed ? "true" : "false")
                << ",\"exitCode\":" << result.exitCode << ",\"timedOut\":" << (result.timedOut ? "true" : "false")
                << ",\"outputLimit\":" << (result.outputLimit ? "true" : "false") << ",\"pdfBytes\":" << bytes
                << ",\"totalProcesses\":" << result.totalProcesses << ",\"activeAfterCleanup\":0"
                << ",\"rootAppContainerTokenVerified\":" << (isolated ? "true" : "false") << "}\n";
            passed &= completed;
            std::wcout << name << L" export completed=" << completed << std::endl;
        } catch (const std::exception& error) {
            std::ofstream(root / (name + L".err")) << error.what() << '\n';
            std::wcout << name << L" failed; retained diagnostic." << std::endl;
            passed = false;
        }
    }
    return passed;
}

// Separate ordinary-process control with the exact redirected environment of
// the failed AppContainer case. Reuses only its verified runtime copy.
bool OfficeRedirectedEnvironmentControl(const fs::path& root) {
    const auto profile = root / L"writable" / L"ec";
    Require(!fs::exists(profile), "Use an unexecuted redirected-environment control");
    fs::create_directories(profile / L"user");
    fs::copy_file(root.parent_path() / L"office-fixtures" / L"settings.xcu", profile / L"user" / L"registrymodifications.xcu");
    wchar_t uri[32768]{}; DWORD length = static_cast<DWORD>(std::size(uri));
    Require(SUCCEEDED(UrlCreateFromPathW(profile.c_str(), uri, &length, 0)), "Create control profile URI");
    const auto environment = EnvironmentBlock(AccessEnvironmentValues(root, true));
    const auto previousMode = SetErrorMode(SEM_FAILCRITICALERRORS | SEM_NOGPFAULTERRORBOX | SEM_NOOPENFILEERRORBOX);
    struct ErrorModeGuard { UINT value; ~ErrorModeGuard() { SetErrorMode(value); } } errorMode{ previousMode };
    const auto started = GetTickCount64();
    const auto result = Run(root.parent_path() / L"office" / L"program" / L"soffice.com",
        { std::wstring(L"-env:UserInstallation=") + uri, L"--headless", L"--nologo", L"--nodefault",
          L"--norestore", L"--unaccept=all", L"--terminate_after_init" }, root, nullptr, 60000, {}, &environment);
    const bool passed = result.exitCode == 0 && !result.timedOut && !result.outputLimit;
    std::ofstream(root / L"redirected-control.log") << result.output;
    std::ofstream(root / L"redirected-control.json") << "{\"passed\":" << (passed ? "true" : "false")
        << ",\"exitCode\":" << result.exitCode << ",\"timedOut\":" << (result.timedOut ? "true" : "false")
        << ",\"outputLimit\":" << (result.outputLimit ? "true" : "false") << ",\"milliseconds\":" << GetTickCount64() - started
        << ",\"totalProcesses\":" << result.totalProcesses << ",\"activeAfterCleanup\":0}\n";
    return passed;
}
